### ISSUE TITLE
The bin folder does not contain antibody.linuxgccrelease

### ISSUE THREAD

**Issue by Tangbbmc** [RosettaCommons/rosetta#137]
I have downloaded the Rosetta_3.14_Ubuntu_binaries (20G) file from website https://downloads.rosettacommons.org/downloads/academic/3.14/. When the file was decompressed, I found that the bin folder of source does not contain antibody.linuxgccrelease module, which can be used to predict antibody structure.

**Comment by roccomoretti** [comment]
The name of Rosetta executables contain details about the compilation conditions. The distributed binaries are statically compiled, so they'll be `antibody.static.linuxgccrelease` -- Unless you need special features, any executable that matches in the first element should work.

**Comment by Tangbbmc** [comment]
> The name of Rosetta executables contain details about the compilation conditions. The distributed binaries are statically compiled, so they'll be `antibody.static.linuxgccrelease` -- Unless you need special features, any executable that matches in the first element should work.

Ok. Thank you! I want to predict the 3D structure of a single mutant of antibody using the experimentally measured wild-type structure as template. Could you tell me how to run command with antibody.static.linuxgccrelease? Thank you!

**Comment by roccomoretti** [comment]
I don't know if we have a demo or tutorial which uses the `antibody` application, but the [documentation](https://docs.rosettacommons.org/docs/latest/application_documentation/antibody/antibody-protocol) and the references listed therein would be a good starting point. (Keep in mind that many Rosetta papers have "protocol captures" in the supplemental material, which provide example commands.)

**Comment by Tangbbmc** [comment]
Ok. Thank you very much for your suggestions!


---- Replied Message ----
From  Rocco ***@***.***> Date  08/31/2024 22:36 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [RosettaCommons/rosetta] The bin folder does not contain antibody.linuxgccrelease (Issue #137)  

I don't know if we have a demo or tutorial which uses the antibody application, but the documentation and the references listed therein would be a good starting point. (Keep in mind that many Rosetta papers have "protocol captures" in the supplemental material, which provide example commands.)

**Comment by roccomoretti** [comment]
Marking this as "closed", as I hope your issue has been addressed. If that assessment is incorrect, feel free to re-open or open up a new issue or discussion with more details.
