### ISSUE TITLE
When compiling rosetta 3.1.4, the following errors were found.

### ISSUE THREAD

**Issue by Tangbbmc** [RosettaCommons/rosetta#138]
dell@dell-OptiPlex-Tower-Plus-7010:~/Documents/Software/rosetta.source.release-371/main/source$ python3 ./scons.py -j30 mode=release bin extras=mpi
scons: Reading SConscript files ...
Running versioning script ... Release package detected, using rosetta/main/.release.json to acquire version information...
Done. (0.0 seconds)
./update_options.sh: line 8: python: command not found
Traceback (most recent call last):
  File "/home/dell/Documents/Software/rosetta.source.release-371/main/source/SConstruct", line 196, in main
    SConscript("SConscript", "build")
  File "/home/dell/Documents/Software/rosetta.source.release-371/main/source/external/scons-local/scons-local-3.0.4/SCons/Script/SConscript.py", line 667, in __call__
    return method(*args, **kw)
  File "/home/dell/Documents/Software/rosetta.source.release-371/main/source/external/scons-local/scons-local-3.0.4/SCons/Script/SConscript.py", line 604, in SConscript
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/dell/Documents/Software/rosetta.source.release-371/main/source/external/scons-local/scons-local-3.0.4/SCons/Script/SConscript.py", line 284, in _SConscript
    exec(compile(_file_.read(), _file_.name, 'exec'),
  File "/home/dell/Documents/Software/rosetta.source.release-371/main/source/SConscript", line 35, in <module>
    subprocess.check_call(["./update_options.sh"])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./update_options.sh']' returned non-zero exit status 127.
scons: done reading SConscript files.
scons: Building targets ...
scons: `bin' is up to date.
scons: done building targets.

**Comment by roccomoretti** [comment]
`./update_options.sh: line 8: python: command not found` is the operative error message.

The Rosetta compilation expects a Python which is installed under the name `python`. With recent versions of Rosetta this can be either Python2 or Python3. You probably have Python installed, but it might not be under the `python` command (e.g. only available under `python3`). 

One potential fix is to add an symlink alias between `python` and `python3` somewhere in your path. If you're on Ubuntu, the package `python-is-python3` should be able to do this for you.

Alternatively, you can install Conda. Conda is a package which manages personal installations of Python and environments, and keeps them separate from the system python. By default Conda installs an alias between `python` and whichever installed Python version you currently have active. -- This approach would be my personal recommendation, as many of the newer ML-based modeling tools are set up to install with Conda, and if you're doing any structural biology work, you'll likely need Conda sooner or later.

**Comment by Tangbbmc** [comment]
OK. I got it! Thank you for your kind help! Bset wishes!


---- Replied Message ----
From  Rocco ***@***.***> Date  08/31/2024 22:30 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [RosettaCommons/rosetta] When compiling rosetta 3.1.4, the following errors were found. (Issue #138)  

./update_options.sh: line 8: python: command not found is the operative error message.
The Rosetta compilation expects a Python which is installed under the name python. With recent versions of Rosetta this can be either Python2 or Python3. You probably have Python installed, but it might not be under the python command (e.g. only available under python3).
One potential fix is to add an symlink alias between python and python3 somewhere in your path. If you're on Ubuntu, the package python-is-python3 should be able to do this for you.
Alternatively, you can install Conda. Conda is a package which manages personal installations of Python and environments, and keeps them separate from the system python. By default Conda installs an alias between python and whichever installed Python version you currently have active. -- This approach would be my personal recommendation, as many of the newer ML-based modeling tools are set up to install with Conda, and if you're doing any structural biology work, you'll likely need Conda sooner or later.

**Comment by roccomoretti** [comment]
Marking this as "closed", as I hope your issue has been addressed. If that assessment is incorrect, feel free to re-open or open up a new issue or discussion with more details.
