### ISSUE TITLE
Rosetta Commons Website is not properly working

### ISSUE THREAD

**Issue by MuhammadAttaElhamouly** [RosettaCommons/rosetta#143]
Rosetta Commons Website is not properly working

**Comment by MuhammadAttaElhamouly** [comment]
![Screenshot 2024-09-03 161046](https://github.com/user-attachments/assets/83677c59-86ff-4ee3-add8-ead969130ea8)

**Comment by roccomoretti** [comment]
Apologies about that. This should now be fixed, and we're working on ways to make sure it doesn't happen again.

**Comment by MuhammadAttaElhamouly** [comment]
> Apologies about that. This should now be fixed, and we're working on ways to make sure it doesn't happen again.

Thanks a lot
