### ISSUE TITLE
Pyrosetta installation problem

### ISSUE THREAD

**Issue by jjz2023** [RosettaCommons/rosetta#191]
I tried to install pyrosetta with the first commend line. It appeared to work, but error appeared after the second commend line.

>pip install pyrosetta-installer
>python -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyrosetta_installer'

How to fix this?

**Comment by roccomoretti** [comment]
I would guess that there was an issue with downloading and installing the pyrosetta-installer package.

When you run the first line, what is the output? Are there any error or warning messages?

Here's what I get for a successful install:
```
Collecting pyrosetta_installer
  Downloading pyrosetta_installer-0.1.1-py3-none-any.whl.metadata (1.6 kB)
Downloading pyrosetta_installer-0.1.1-py3-none-any.whl (3.9 kB)
Installing collected packages: pyrosetta_installer
Successfully installed pyrosetta_installer-0.1.1
```

If you're missing that last "Successfully installed" line, then something went wrong with the pip install, and you should check the warning and error messages to see what needs to be fixed.

**Comment by jjz2023** [comment]
Yes, I got the five lines as you listed after I executed "pip install pyrosetta-installer". After I ran the second commend line "python -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'", I got the following three lines:
Traceback (most recent call last):
File "", line 1, in
ModuleNotFoundError: No module named 'pyrosetta_installer'

**Comment by roccomoretti** [comment]
That's odd. The best I can guess is that the python associated with your `pip` is not the python associated with your `python`.

If you can run a `which pip` and a `which python`, that should tell you where the programs your shell is running for each are located. Ideally they should be in the same directory.

Another approach is to run pip with the `python` command. Try a `python -m pip install pyrosetta-installer` -- that should run the pip associated with your `python` command. If that command fails, try running `python -m ensurepip --upgrade` and then re-running it.

**Comment by jjz2023** [comment]
Thanks for your suggestions. I have two versions (3.9 and 3.12) of python in my miniconda3/lib and python_installer was in both site_packages folders. I ran with specific version of python as "python3.9 -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'" commend line and it worked. Thanks again.
