### ISSUE TITLE
Errors when run  docking_protocol.linuxgccrelease 

### ISSUE THREAD

**Issue by Luckken21** [RosettaCommons/rosetta#96]
[ERROR] Exception caught by JobDistributor for job test1_A_local_dock_0001

[ ERROR ]: Caught exception:

File: src/core/conformation/Conformation.hh:514
[ ERROR ] UtilityExitException
ERROR: Error in core::conformation::Conformation::residue(): The sequence position requested was greater than the number of residues in the pose.
I meet the problem when  using ~/Rosseta/rosetta.source.release-371/main/source/bin/docking_protocol.linuxgccrelease -in:file:s input_files/test1_A.pdb -in:file:native input_files/test_A.pdb -nstruct 1 -partners A_B -dock_pert 3 8 -ex1 -ex2aro -out:path:all output_files -out:suffix _local_dock
Thanks a lot if you can help me

**Comment by Luckken21** [comment]
[ERROR] Exception caught by JobDistributor for job test1_A_local_dock_0001

[ ERROR ]: Caught exception:


File: src/core/conformation/Conformation.hh:514
[ ERROR ] UtilityExitException
ERROR: Error in core::conformation::Conformation::residue(): The sequence position requested was greater than the number of residues in the pose.
I have solve the problem by using ~/Rosseta/rosetta.source.release-371/main/source/bin/docking_protocol.linuxgccrelease -in:file:s input_files/test1_A.pdb -in:file:native input_files/test_A.pdb -nstruct 1 -partners A_B -dock_pert 3 8 -ex1 -ex2aro -out:path:all output_files -out:suffix _local_dock, but I meet with a new problem

**Comment by roccomoretti** [comment]
The `-partners A_B` specifies you want to dock chain B against chain A. Does your input file (input_files/test1_A.pdb) contain both chain A and chain B? Both chains need to be present in the input file, but don't (necessarily) need to be in the correct relative orientation.

**Comment by roccomoretti** [comment]
Marking this as "closed", as I hope your issue has been addressed. If that assessment is incorrect, feel free to re-open or open up a new issue with more details.
